### ISSUE TITLE
Redirecting Social media links

### ISSUE THREAD

**Issue by Hasthikagirihagama** [acf-sack/Splendour#10]
**Is your feature request related to a problem? Please describe.**
The Social media buttons are redirected inside the the same page itself when clicked

**Describe the solution you'd like**
Redirect the Social media links to a New Tab

**Additional context**

https://github.com/acf-sack/Splendour/assets/70457601/f0dd51b3-0ec5-4d72-8157-9415c2fdacbb

**Are you working on it?**
No

**Comment by YoshithaRathnayake** [comment]
Assign me 😊 @Hasthikagirihagama

**Comment by YoshithaRathnayake** [comment]
#Close
